# -*- coding: utf-8 -*-
"""Shared constants for OMP workflow modes."""

DEFAULT_MAX_ITERATIONS = 30

ULTRAQA_MAX_CYCLES = 5
ULTRAQA_MAX_SAME_FAILURE = 3

AUTOPILOT_MAX_PHASE_ITERATIONS = 10
AUTOPILOT_MAX_VALIDATION_ROUNDS = 3

RALPH_MAX_ITERATIONS = 20
RALPH_MAX_SAME_ISSUE = 3

TEAM_MAX_FIX_ATTEMPTS = 3
TEAM_MAX_ITERATIONS = 30
