# -*- coding: utf-8 -*-
"""ToolRegistry — Single source of truth for tool metadata.

Each tool declares on registration:
    - Type (file / network / shell / internal)
    - Target parameter name (file_path / command / url …)
    - Python function name → policy tool name mapping

Relationship with policy.yaml:
    ToolRegistry: what a tool is (type, parameter name)
        → static, registered in code
    policy.yaml:  what a tool can do (rules, default perms)
        → dynamic, generated by user/approve
"""

from __future__ import annotations

import logging
import os
from typing import Any, Dict, List

logger = logging.getLogger(__name__)


class ToolRegistry:
    """Tool metadata registry."""

    def __init__(self) -> None:
        self._types: Dict[str, str] = {}
        self._target_params: Dict[str, str] = {}
        self._python_name_map: Dict[str, str] = {}
        # Tools whose target should combine path + pattern
        # (e.g. Glob: pattern is a file glob, so path+pattern
        # forms a complete filesystem path pattern for rule matching).
        self._pattern_params: Dict[str, str] = {}
        # Tools that refuse to run (fail closed) unless a sandbox_config is
        # supplied — as opposed to shell tools like Bash that execute directly
        # when unsandboxed. See ``requires_sandbox`` for why this matters.
        self._sandbox_required: Dict[str, bool] = {}

    def register(
        self,
        tool_name: str,
        tool_type: str,
        target_param: str,
        pattern_param: str = "",
        sandbox_required: bool = False,
    ) -> None:
        """Register a tool.

        Args:
            tool_name: policy-layer tool name, e.g. "Read"
            tool_type: "file" | "network" | "shell" | "internal"
            target_param: target parameter name, e.g. "file_path", "command"
            pattern_param: for file-search tools (e.g. Glob), the parameter
                name holding the glob pattern. When set, ``extract_target``
                combines path + pattern into a single filesystem path pattern.
            sandbox_required: ``True`` for tools that **fail closed** without a
                ``sandbox_config`` (e.g. ``recall_history_python``, which runs
                model-authored Python and returns ``DENIED`` when no sandbox is
                supplied). Distinct from mere shell-type: ``Bash`` is shell but
                fail-*open* — it executes unsandboxed when no config is given.
                Consumed by the approval_level=OFF path, which must still
                compile a sandbox for these tools instead of letting them dead
                -end in a sandbox-violation → approval loop.
        """
        self._types[tool_name] = tool_type
        self._target_params[tool_name] = target_param
        if pattern_param:
            self._pattern_params[tool_name] = pattern_param
        if sandbox_required:
            self._sandbox_required[tool_name] = True

    def register_python_name(self, python_name: str, policy_name: str) -> None:
        """Register a python function name → policy tool name mapping."""
        self._python_name_map[python_name] = policy_name

    def get_type(self, tool_name: str) -> str:
        """Return the tool's type. Returns "unknown" if not registered."""
        return self._types.get(tool_name, "unknown")

    def get_target_param(self, tool_name: str) -> str:
        """Return the tool's target parameter name.

        Returns "" if not registered.
        """
        return self._target_params.get(tool_name, "")

    def requires_sandbox(self, tool_name: str) -> bool:
        """Whether the tool fails closed without a ``sandbox_config``.

        ``True`` only for tools that refuse to run unsandboxed (the REPL).
        Returns ``False`` for unregistered tools and for fail-open shell
        tools like ``Bash`` that execute directly when no sandbox is given.
        """
        return self._sandbox_required.get(tool_name, False)

    def python_to_policy_name(self, python_name: str) -> str:
        """Map a python function name to a policy tool name.

        Checks explicit mapping first; if no mapping exists, converts
        snake_case → PascalCase.
        """
        override = self._python_name_map.get(python_name)
        if override:
            return override
        parts = python_name.split("_")
        return "".join(p.capitalize() for p in parts)

    def extract_target(
        self,
        tool_name: str,
        input_data: dict[str, Any],
        workspace_dir: str = "",
    ) -> str:
        """Extract the target from tool call arguments."""
        param = self.get_target_param(tool_name)
        if not param:
            return ""

        # 1) Get base path from input
        path = input_data.get(param, "")
        path = str(path) if path else ""

        # Expand a leading ``~`` to the user's home directory
        if path:
            path = os.path.expanduser(path)

        # 2) For file tools, resolve empty/relative path using workspace_dir
        if self._types.get(tool_name) == "file" and workspace_dir:
            if not path:
                path = workspace_dir
            elif not os.path.isabs(path):
                path = os.path.join(workspace_dir, path)

        # 3) Append pattern for file-search tools (e.g. Glob)
        pattern_param = self._pattern_params.get(tool_name)
        if pattern_param:
            pattern = input_data.get(pattern_param, "")
            if pattern:
                path = (
                    os.path.join(path, str(pattern)) if path else str(pattern)
                )

        return path

    def get_all_tool_names(self) -> List[str]:
        """Return all registered tool names."""
        return list(self._types.keys())


# ---------------------------------------------------------------------------
# Shared registration helpers
# ---------------------------------------------------------------------------


def snake_to_pascal(name: str) -> str:
    """Convert ``snake_case`` to ``PascalCase``."""
    return "".join(p.capitalize() for p in name.split("_"))


def register_tool_governance(
    registry: ToolRegistry,
    python_name: str,
    tool_type: str,
    target_param: str = "",
    policy_name: str = "",
    pattern_param: str = "",
    sandbox_required: bool = False,
) -> str:
    """Register one tool into the governance registry (idempotent).

    Used by:
    - builtin ``@tool_descriptor`` scan (``_register_from_descriptors``)
    - ``PluginApi.register_tool`` (issue #6114)
    - goal-mode ``register_goal_tools_governance``

    Returns the policy-layer tool name that was registered
    (or already present).
    """
    pname = policy_name or snake_to_pascal(python_name)
    if registry.get_type(pname) == "unknown":
        registry.register(
            pname,
            tool_type,
            target_param,
            pattern_param=pattern_param,
            sandbox_required=sandbox_required,
        )
    registry.register_python_name(python_name, pname)
    return pname


def _register_from_descriptors(registry: ToolRegistry) -> None:
    """Register builtins that declare governance.tool_type on descriptors."""
    try:
        # Side-effect import so @tool_descriptor registrations run.
        import qwenpaw.agents.tools as _agents_tools  # noqa: F401
        from ..runtime.tool_registry import get_builtin_tool_funcs

        _ = _agents_tools
    except Exception as exc:  # noqa: BLE001
        logger.debug(
            "Skipping descriptor governance registration: %s",
            exc,
        )
        return

    for fn in get_builtin_tool_funcs():
        desc = getattr(fn, "_tool_descriptor", None)
        if desc is None:
            continue
        gov = getattr(desc, "governance", None)
        if gov is None or not gov.tool_type:
            continue
        register_tool_governance(
            registry,
            python_name=desc.name,
            tool_type=gov.tool_type,
            target_param=gov.target_param,
            policy_name=gov.policy_name,
            pattern_param=gov.pattern_param,
            sandbox_required=gov.fail_without_sandbox,
        )


def _register_non_descriptor_tools(registry: ToolRegistry) -> None:
    """Tools that intentionally skip ``@tool_descriptor`` auto-collection."""
    # Scroll strategy tools — hand-built descriptors, not global builtins.
    register_tool_governance(
        registry,
        python_name="recall_history",
        tool_type="internal",
        target_param="op",
        policy_name="RecallHistory",
    )
    register_tool_governance(
        registry,
        python_name="recall_history_python",
        tool_type="shell",
        target_param="source",
        policy_name="RecallHistoryPython",
        sandbox_required=True,
    )
    # Memory manager tool — registered dynamically outside agents.tools.
    register_tool_governance(
        registry,
        python_name="memory_search",
        tool_type="internal",
        target_param="",
        policy_name="MemorySearch",
    )


def assert_no_governance_gaps() -> list[str]:
    """Return policy names of descriptor tools missing from governance.

    Tools with empty ``governance.tool_type`` are skipped (not yet migrated
    or intentionally using another registration path).
    """
    from ..runtime.tool_registry import get_builtin_tool_funcs

    gaps: list[str] = []
    registry = DEFAULT_REGISTRY
    for fn in get_builtin_tool_funcs():
        desc = getattr(fn, "_tool_descriptor", None)
        if desc is None:
            continue
        gov = getattr(desc, "governance", None)
        if gov is None or not gov.tool_type:
            continue
        pname = gov.policy_name or snake_to_pascal(desc.name)
        if registry.get_type(pname) == "unknown":
            gaps.append(pname)
            logger.error(
                "Governance gap: tool %r (policy %r) is runtime-registered "
                "but missing from the governance registry (Phase 0 DENY).",
                desc.name,
                pname,
            )
    return gaps


# ---------------------------------------------------------------------------
# Default registry (lazy singleton)
# ---------------------------------------------------------------------------


def _create_default_registry() -> ToolRegistry:
    """Create and populate the default ToolRegistry."""
    registry = ToolRegistry()
    _register_from_descriptors(registry)
    _register_non_descriptor_tools(registry)
    return registry


class _LazyDefaultRegistry:
    """Proxy that builds the real registry on first attribute access.

    Keeps the public name ``DEFAULT_REGISTRY`` stable for call sites while
    delaying construction until after ``agents.tools`` imports can run.
    """

    __slots__ = ("_instance",)

    def __init__(self) -> None:
        object.__setattr__(self, "_instance", None)

    def _get(self) -> ToolRegistry:
        inst = object.__getattribute__(self, "_instance")
        if inst is None:
            inst = _create_default_registry()
            object.__setattr__(self, "_instance", inst)
        return inst

    def __getattr__(self, name: str) -> Any:
        return getattr(self._get(), name)

    def _reset_for_tests(self) -> None:
        """Drop the cached instance (test helper only)."""
        object.__setattr__(self, "_instance", None)


DEFAULT_REGISTRY: Any = _LazyDefaultRegistry()
